-- ============================================================
-- Migration 003: Gift Cards, Customer Tabs, Order Notes,
--                Inventory, Batch Settlement
-- Restaurant POS - Self-Hosted Edition
--
-- Supports: MySQL 5.7+, PostgreSQL 9.5+
-- Run this AFTER migration-002-refunds-timeclock-held.sql
-- ============================================================

-- =============================================
-- 1. Gift Card Table
-- =============================================
CREATE TABLE IF NOT EXISTS GIFT_CARD (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    CARD_NUMBER VARCHAR(50) NOT NULL,
    BALANCE DECIMAL(12,2) NOT NULL DEFAULT 0,
    ORIGINAL_AMOUNT DECIMAL(12,2) NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    ACTIVATED_BY INTEGER,
    ACTIVATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_USED_AT TIMESTAMP,
    EXPIRES_AT DATE,
    PRIMARY KEY (ID),
    UNIQUE (CARD_NUMBER)
);

CREATE INDEX IF NOT EXISTS IDX_GC_NUMBER ON GIFT_CARD (CARD_NUMBER);
CREATE INDEX IF NOT EXISTS IDX_GC_STATUS ON GIFT_CARD (STATUS);

-- =============================================
-- 2. Gift Card Transaction Log
-- =============================================
CREATE TABLE IF NOT EXISTS GIFT_CARD_TRANSACTION (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    CARD_NUMBER VARCHAR(50) NOT NULL,
    TRANSACTION_TYPE VARCHAR(20) NOT NULL,
    AMOUNT DECIMAL(12,2) NOT NULL,
    BALANCE_AFTER DECIMAL(12,2) NOT NULL,
    TICKET_ID INTEGER,
    PROCESSED_BY INTEGER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_GCT_CARD ON GIFT_CARD_TRANSACTION (CARD_NUMBER);
CREATE INDEX IF NOT EXISTS IDX_GCT_DATE ON GIFT_CARD_TRANSACTION (CREATED_AT);

-- =============================================
-- 3. Customer Tab Table
-- =============================================
CREATE TABLE IF NOT EXISTS CUSTOMER_TAB (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    CUSTOMER_NAME VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20),
    EMAIL VARCHAR(100),
    TAB_LIMIT DECIMAL(12,2) DEFAULT 100.00,
    RUNNING_TOTAL DECIMAL(12,2) DEFAULT 0,
    STATUS VARCHAR(20) DEFAULT 'OPEN',
    OPENED_BY INTEGER,
    OPENED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CLOSED_AT TIMESTAMP,
    CLOSED_BY INTEGER,
    NOTES VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_TAB_STATUS ON CUSTOMER_TAB (STATUS);
CREATE INDEX IF NOT EXISTS IDX_TAB_PHONE ON CUSTOMER_TAB (PHONE);

-- =============================================
-- 4. Tab-Ticket Association
-- =============================================
CREATE TABLE IF NOT EXISTS TAB_TICKET (
    TAB_ID INTEGER NOT NULL,
    TICKET_ID INTEGER NOT NULL,
    AMOUNT DECIMAL(12,2),
    ADDED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (TAB_ID, TICKET_ID)
);

-- =============================================
-- 5. Order Notes Table
-- =============================================
CREATE TABLE IF NOT EXISTS TICKET_NOTE (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    TICKET_ID INTEGER NOT NULL,
    NOTE_TYPE VARCHAR(20) DEFAULT 'TICKET',
    ITEM_INDEX INTEGER,
    ITEM_NAME VARCHAR(100),
    NOTE_TEXT TEXT NOT NULL,
    CREATED_BY INTEGER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_TN_TICKET ON TICKET_NOTE (TICKET_ID);

-- =============================================
-- 6. Add note column to TICKET table
-- =============================================
ALTER TABLE TICKET ADD COLUMN IF NOT EXISTS TICKET_NOTE TEXT;

-- =============================================
-- 7. Inventory / Stock Tracking
-- =============================================
CREATE TABLE IF NOT EXISTS INVENTORY (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    MENU_ITEM_ID INTEGER NOT NULL,
    ITEM_NAME VARCHAR(100),
    STOCK_QTY INTEGER DEFAULT 50,
    LOW_THRESHOLD INTEGER DEFAULT 5,
    PAR_LEVEL INTEGER DEFAULT 20,
    UNIT VARCHAR(20) DEFAULT 'each',
    LAST_RESTOCKED TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE (MENU_ITEM_ID)
);

CREATE TABLE IF NOT EXISTS INVENTORY_LOG (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    MENU_ITEM_ID INTEGER NOT NULL,
    CHANGE_TYPE VARCHAR(20) NOT NULL,
    QTY_CHANGE INTEGER NOT NULL,
    QTY_AFTER INTEGER NOT NULL,
    REASON VARCHAR(255),
    TICKET_ID INTEGER,
    CHANGED_BY INTEGER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_INV_ITEM ON INVENTORY (MENU_ITEM_ID);
CREATE INDEX IF NOT EXISTS IDX_INVLOG_ITEM ON INVENTORY_LOG (MENU_ITEM_ID);
CREATE INDEX IF NOT EXISTS IDX_INVLOG_DATE ON INVENTORY_LOG (CREATED_AT);

-- =============================================
-- 8. Batch Settlement Table
-- =============================================
CREATE TABLE IF NOT EXISTS BATCH_SETTLEMENT (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    BATCH_NUMBER VARCHAR(50) NOT NULL,
    TERMINAL_ID VARCHAR(50),
    TOTAL_AMOUNT DECIMAL(12,2) NOT NULL,
    TRANSACTION_COUNT INTEGER NOT NULL,
    TOTAL_TIPS DECIMAL(12,2) DEFAULT 0,
    STATUS VARCHAR(20) DEFAULT 'COMPLETED',
    SETTLED_BY INTEGER,
    SETTLED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE (BATCH_NUMBER)
);

CREATE INDEX IF NOT EXISTS IDX_BS_DATE ON BATCH_SETTLEMENT (SETTLED_AT);

-- Add batch settlement tracking to TICKET
ALTER TABLE TICKET ADD COLUMN IF NOT EXISTS BATCH_SETTLED BOOLEAN DEFAULT FALSE;
ALTER TABLE TICKET ADD COLUMN IF NOT EXISTS BATCH_NUMBER VARCHAR(50);
ALTER TABLE TICKET ADD COLUMN IF NOT EXISTS SETTLED_AT TIMESTAMP;

-- =============================================
-- 9. Tip Adjustment Tracking
-- =============================================
ALTER TABLE TICKET ADD COLUMN IF NOT EXISTS TIP_AMOUNT DECIMAL(12,2) DEFAULT 0;
ALTER TABLE TICKET ADD COLUMN IF NOT EXISTS TIP_ADJUSTED BOOLEAN DEFAULT FALSE;
ALTER TABLE TICKET ADD COLUMN IF NOT EXISTS TIP_ADJUSTED_AT TIMESTAMP;
ALTER TABLE TICKET ADD COLUMN IF NOT EXISTS TIP_ADJUSTED_BY INTEGER;

-- =============================================
-- 10. Language Preference
-- =============================================
ALTER TABLE EMPLOYEE ADD COLUMN IF NOT EXISTS PREFERRED_LANGUAGE VARCHAR(5) DEFAULT 'en';

-- =============================================
-- 11. Quick Service Mode Setting
-- =============================================
INSERT INTO CASH_DISCOUNT_CONFIG (CONFIG_KEY, CONFIG_VALUE) VALUES
    ('quickServiceMode', 'false')
ON DUPLICATE KEY UPDATE CONFIG_VALUE = CONFIG_VALUE;
