-- ============================================================
-- Migration 002: Refunds, Time Clock, Held Orders
-- Restaurant POS - Self-Hosted Edition
--
-- Supports: MySQL 5.7+, PostgreSQL 9.5+
-- Run this AFTER migration-cashdiscount-paybotx.sql
-- ============================================================

-- =============================================
-- 1. Refund Tracking Table
-- =============================================
CREATE TABLE IF NOT EXISTS REFUND (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    TICKET_ID INTEGER NOT NULL,
    AMOUNT DECIMAL(12,2) NOT NULL,
    REFUND_TYPE VARCHAR(20) NOT NULL DEFAULT 'FULL',
    REASON VARCHAR(255),
    PAYMENT_METHOD VARCHAR(20),
    PROCESSED_BY VARCHAR(100),
    PROCESSED_BY_ID INTEGER,
    STATUS VARCHAR(20) DEFAULT 'COMPLETED',
    ORIGINAL_TRANSACTION_ID INTEGER,
    REFUND_TRANSACTION_ID INTEGER,
    NOTES TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_REFUND_TICKET ON REFUND (TICKET_ID);
CREATE INDEX IF NOT EXISTS IDX_REFUND_DATE ON REFUND (CREATED_AT);
CREATE INDEX IF NOT EXISTS IDX_REFUND_PROCESSED_BY ON REFUND (PROCESSED_BY_ID);

-- =============================================
-- 2. Add refund columns to TICKET table
-- =============================================
ALTER TABLE TICKET ADD COLUMN IF NOT EXISTS REFUND_STATUS VARCHAR(20);
ALTER TABLE TICKET ADD COLUMN IF NOT EXISTS REFUNDED_AMOUNT DECIMAL(12,2) DEFAULT 0;
ALTER TABLE TICKET ADD COLUMN IF NOT EXISTS REFUNDED_AT TIMESTAMP;

-- =============================================
-- 3. Time Clock / Labor Tracking
-- =============================================
CREATE TABLE IF NOT EXISTS TIME_CLOCK (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    EMPLOYEE_ID INTEGER NOT NULL,
    EMPLOYEE_NAME VARCHAR(100),
    ROLE VARCHAR(50),
    CLOCK_IN TIMESTAMP NOT NULL,
    CLOCK_OUT TIMESTAMP,
    HOURS_WORKED DECIMAL(8,2),
    HOURLY_RATE DECIMAL(8,2),
    BREAK_MINUTES INTEGER DEFAULT 0,
    NOTES VARCHAR(255),
    APPROVED_BY INTEGER,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_TC_EMPLOYEE ON TIME_CLOCK (EMPLOYEE_ID);
CREATE INDEX IF NOT EXISTS IDX_TC_CLOCK_IN ON TIME_CLOCK (CLOCK_IN);
CREATE INDEX IF NOT EXISTS IDX_TC_STATUS ON TIME_CLOCK (STATUS);

-- =============================================
-- 4. Employee / Staff Table
-- =============================================
CREATE TABLE IF NOT EXISTS EMPLOYEE (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    PIN_HASH VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    DISPLAY_NAME VARCHAR(100),
    ROLE VARCHAR(50) NOT NULL DEFAULT 'SERVER',
    HOURLY_RATE DECIMAL(8,2) DEFAULT 0,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    LAST_LOGIN TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_EMP_ROLE ON EMPLOYEE (ROLE);
CREATE INDEX IF NOT EXISTS IDX_EMP_ACTIVE ON EMPLOYEE (IS_ACTIVE);

-- Default employees (PINs are stored as plain for demo; hash in production)
INSERT INTO EMPLOYEE (PIN_HASH, FIRST_NAME, LAST_NAME, DISPLAY_NAME, ROLE, HOURLY_RATE) VALUES
    ('1234', 'Maria', 'G.', 'Maria G.', 'MANAGER', 28.00),
    ('1111', 'John', 'D.', 'John D.', 'SERVER', 12.00),
    ('2222', 'Sarah', 'K.', 'Sarah K.', 'SERVER', 12.00),
    ('3333', 'Mike', 'R.', 'Mike R.', 'CASHIER', 15.00),
    ('4444', 'Lisa', 'T.', 'Lisa T.', 'BARTENDER', 14.00),
    ('5555', 'Carlos', 'M.', 'Carlos M.', 'KITCHEN', 16.00),
    ('9999', 'Admin', '', 'Admin', 'ADMIN', 0.00);

-- =============================================
-- 5. Held Orders Table
-- =============================================
CREATE TABLE IF NOT EXISTS HELD_ORDER (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    ORIGINAL_TICKET_ID INTEGER,
    ORDER_TYPE VARCHAR(20) DEFAULT 'DINE_IN',
    TABLE_NUMBER VARCHAR(10),
    SERVER_ID INTEGER,
    SERVER_NAME VARCHAR(100),
    ITEMS_JSON TEXT NOT NULL,
    DISCOUNT_JSON TEXT,
    SUBTOTAL DECIMAL(12,2),
    NOTE VARCHAR(255),
    HELD_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    RECALLED_AT TIMESTAMP,
    STATUS VARCHAR(20) DEFAULT 'HELD',
    PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_HO_STATUS ON HELD_ORDER (STATUS);
CREATE INDEX IF NOT EXISTS IDX_HO_SERVER ON HELD_ORDER (SERVER_ID);

-- =============================================
-- 6. Discount / Promo Code Table
-- =============================================
CREATE TABLE IF NOT EXISTS PROMO_CODE (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    CODE VARCHAR(50) NOT NULL,
    DISCOUNT_TYPE VARCHAR(20) NOT NULL,
    DISCOUNT_VALUE DECIMAL(8,2) NOT NULL,
    DESCRIPTION VARCHAR(255),
    MIN_ORDER_AMOUNT DECIMAL(12,2) DEFAULT 0,
    MAX_USES INTEGER DEFAULT 0,
    CURRENT_USES INTEGER DEFAULT 0,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    VALID_FROM DATE,
    VALID_UNTIL DATE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE (CODE)
);

INSERT INTO PROMO_CODE (CODE, DISCOUNT_TYPE, DISCOUNT_VALUE, DESCRIPTION, MIN_ORDER_AMOUNT) VALUES
    ('WELCOME10', 'PERCENT', 10.00, '10% off your order', 0),
    ('LUNCH5', 'FIXED', 5.00, '$5 off lunch', 20.00),
    ('HAPPY25', 'PERCENT', 25.00, '25% Happy Hour', 0),
    ('FREESHIP', 'DELIVERY', 0.00, 'Free delivery', 15.00),
    ('BOGO50', 'PERCENT', 50.00, '50% off (BOGO)', 0);

-- =============================================
-- 7. Delivery Order Details
-- =============================================
CREATE TABLE IF NOT EXISTS DELIVERY_ORDER (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    TICKET_ID INTEGER NOT NULL,
    CUSTOMER_NAME VARCHAR(100),
    PHONE VARCHAR(20),
    ADDRESS TEXT,
    DELIVERY_INSTRUCTIONS TEXT,
    DELIVERY_FEE DECIMAL(8,2) DEFAULT 0,
    DELIVERY_STATUS VARCHAR(20) DEFAULT 'PENDING',
    DRIVER_NAME VARCHAR(100),
    ESTIMATED_DELIVERY TIMESTAMP,
    DELIVERED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_DO_TICKET ON DELIVERY_ORDER (TICKET_ID);
CREATE INDEX IF NOT EXISTS IDX_DO_STATUS ON DELIVERY_ORDER (DELIVERY_STATUS);

-- =============================================
-- 8. Add discount columns to TICKET table
-- =============================================
ALTER TABLE TICKET ADD COLUMN IF NOT EXISTS DISCOUNT_TYPE VARCHAR(20);
ALTER TABLE TICKET ADD COLUMN IF NOT EXISTS DISCOUNT_VALUE DECIMAL(8,2) DEFAULT 0;
ALTER TABLE TICKET ADD COLUMN IF NOT EXISTS DISCOUNT_AMOUNT DECIMAL(12,2) DEFAULT 0;
ALTER TABLE TICKET ADD COLUMN IF NOT EXISTS DISCOUNT_REASON VARCHAR(255);
ALTER TABLE TICKET ADD COLUMN IF NOT EXISTS PROMO_CODE VARCHAR(50);
ALTER TABLE TICKET ADD COLUMN IF NOT EXISTS DELIVERY_FEE DECIMAL(8,2) DEFAULT 0;
ALTER TABLE TICKET ADD COLUMN IF NOT EXISTS DELIVERY_ADDRESS TEXT;

-- =============================================
-- 9. Role Permissions Table
-- =============================================
CREATE TABLE IF NOT EXISTS ROLE_PERMISSION (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    ROLE_NAME VARCHAR(50) NOT NULL,
    PERMISSION_KEY VARCHAR(100) NOT NULL,
    IS_ALLOWED BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (ID),
    UNIQUE (ROLE_NAME, PERMISSION_KEY)
);

INSERT INTO ROLE_PERMISSION (ROLE_NAME, PERMISSION_KEY, IS_ALLOWED) VALUES
    ('ADMIN', 'POS', TRUE), ('ADMIN', 'KITCHEN', TRUE), ('ADMIN', 'TABLES', TRUE),
    ('ADMIN', 'TICKETS', TRUE), ('ADMIN', 'REPORTS', TRUE), ('ADMIN', 'VOID_TICKET', TRUE),
    ('ADMIN', 'DISCOUNT', TRUE), ('ADMIN', 'SETTINGS', TRUE), ('ADMIN', 'REFUND', TRUE),
    ('MANAGER', 'POS', TRUE), ('MANAGER', 'KITCHEN', TRUE), ('MANAGER', 'TABLES', TRUE),
    ('MANAGER', 'TICKETS', TRUE), ('MANAGER', 'REPORTS', TRUE), ('MANAGER', 'VOID_TICKET', TRUE),
    ('MANAGER', 'DISCOUNT', TRUE), ('MANAGER', 'SETTINGS', TRUE), ('MANAGER', 'REFUND', TRUE),
    ('SERVER', 'POS', TRUE), ('SERVER', 'TABLES', TRUE), ('SERVER', 'TICKETS', TRUE),
    ('CASHIER', 'POS', TRUE), ('CASHIER', 'TICKETS', TRUE), ('CASHIER', 'DISCOUNT', TRUE),
    ('BARTENDER', 'POS', TRUE), ('BARTENDER', 'TICKETS', TRUE),
    ('KITCHEN', 'KITCHEN', TRUE);

-- =============================================
-- 10. Modifier Groups and Options
-- =============================================
CREATE TABLE IF NOT EXISTS MODIFIER_GROUP (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    LABEL VARCHAR(100),
    IS_REQUIRED BOOLEAN DEFAULT FALSE,
    MAX_SELECTIONS INTEGER DEFAULT 1,
    SORT_ORDER INTEGER DEFAULT 0,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS MODIFIER_OPTION (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    GROUP_ID INTEGER NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    EXTRA_PRICE DECIMAL(8,2) DEFAULT 0,
    SORT_ORDER INTEGER DEFAULT 0,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (ID),
    FOREIGN KEY (GROUP_ID) REFERENCES MODIFIER_GROUP(ID)
);

CREATE TABLE IF NOT EXISTS MENU_ITEM_MODIFIER (
    MENU_ITEM_ID INTEGER NOT NULL,
    MODIFIER_GROUP_ID INTEGER NOT NULL,
    PRIMARY KEY (MENU_ITEM_ID, MODIFIER_GROUP_ID)
);

-- =============================================
-- 11. Update DAILY_SALES_SUMMARY for new fields
-- =============================================
ALTER TABLE DAILY_SALES_SUMMARY ADD COLUMN IF NOT EXISTS DELIVERY_FEES DECIMAL(12,2) DEFAULT 0;
ALTER TABLE DAILY_SALES_SUMMARY ADD COLUMN IF NOT EXISTS DELIVERY_COUNT INTEGER DEFAULT 0;
ALTER TABLE DAILY_SALES_SUMMARY ADD COLUMN IF NOT EXISTS PROMO_DISCOUNT_TOTAL DECIMAL(12,2) DEFAULT 0;
ALTER TABLE DAILY_SALES_SUMMARY ADD COLUMN IF NOT EXISTS LABOR_HOURS DECIMAL(8,2) DEFAULT 0;
ALTER TABLE DAILY_SALES_SUMMARY ADD COLUMN IF NOT EXISTS LABOR_COST DECIMAL(12,2) DEFAULT 0;
